MvcProject/MvcProject/Controllers/BlogPostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.Extensions.Configuration.UserSecrets;
using MvcProject.Models;
using MvcProject.Services.BlogPosts;
using MvcProject.Services.Category;
using MvcProject.Services.NewFolder;
using System.Security.Claims;

namespace MvcProject.Controllers
{
    public class BlogPostController : Controller
    {
        private readonly IBlogPostService _blogPostService;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ICategoryService _categoryService;
        private readonly ITagService _tagService;
        public BlogPostController(IBlogPostService blogPostService, UserManager<IdentityUser> userManager, ICategoryService categoryService, ITagService tagservice)
        {
            _blogPostService = blogPostService;
            _userManager = userManager;
            _categoryService = categoryService;
            _tagService = tagservice;
        }

        public IActionResult Index(int id)
        {
            var post = this._blogPostService.FindById(id);
            return View(post);
        }

        [Authorize]
        public IActionResult Create()
        {
            var model = new BlogCategoryViewModel()
            {
                AllCategories = this._categoryService.GetAllCategory(),
                CategoryIds = new List<int>(),
                AllTags = this._tagService.GetAllTag(),
                TagIds = new List<int>()
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(BlogCategoryViewModel model)
        {
            

            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            this._blogPostService.Create(model, userId);

            return Redirect("/");
        }

        [Authorize]
        public IActionResult Read(BlogPostModel model)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var allPost = this._blogPostService.FindAllPostsByUserId(model, userId);
            return View(allPost);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Update()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            BlogPostModel post = this._blogPostService.FindByUserId(userId);
            return View(post);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Update(BlogPostModel model)
        {
            this._blogPostService.Update(model);
            return Redirect("/BlogPost/Read");
        }

        [Authorize]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            this._blogPostService.Delete(id);
            return RedirectToAction("Read");
        }
    }
}

MvcProject/MvcProject/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MvcProject.Data.Entities;
using MvcProject.Models;
using MvcProject.Services.Category;
using System.Security.Claims;

namespace MvcProject.Controllers
{
    public class CategoryController : Controller
    {

        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        [Authorize]
        public IActionResult Index()
        {
            var allCategories = this._categoryService.GetAllCategory();
            return View(allCategories);
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Create(CategoryModel model)
        {
            _categoryService.Create(model);
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        public IActionResult Update(int id)
        {
            var category = _categoryService.GetCategoryById(id);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Update(CategoryModel model)
        {
  
               _categoryService.Update(model);
               return RedirectToAction("Index");
            
        }

        [Authorize]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            this._categoryService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

MvcProject/MvcProject/Controllers/TagController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MvcProject.Models;
using MvcProject.Services.Category;
using MvcProject.Services.NewFolder;

namespace MvcProject.Controllers
{
    public class TagController : Controller
    {
        private readonly ITagService _tagService;

        public TagController(ITagService tagService)
        {
            _tagService = tagService;
        }

        [Authorize]
        public IActionResult Index()
        {
            var allTags = this._tagService.GetAllTag();
            return View(allTags);
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Create(TagModel model)
        {
            _tagService.Create(model);
            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet]
        public IActionResult Update(int id)
        {
            var tag = _tagService.GetTagById(id);

            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Update(TagModel model)
        {

            _tagService.Update(model);
            return RedirectToAction("Index");

        }
        [Authorize]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            this._tagService.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

MvcProject/MvcProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BlogPost" asp-action="Read">My Blogs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tag" asp-action="Index">Tags</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcProject
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>